backend:
    name: git-gateway
    branch: master


media_folder: "static/uploads"
public_folder: "uploads"

collections:
    - name: "post"
      label: "posts"
      folder: "content/post"
      create: true
      slug: "{{year}}-{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Hero Image", name: "hero", widget: image, required: true}
        - {label: "Excerpt", name: "excerpt", widget: "string"}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Authors", name: "authors", widget: hidden, default: Angelo Ortiz Vega}
        - {label: "Body", name: "body", widget: "markdown"}
            


